//! Golden-value regression test for body / moon / minor-body / comet positions.
//!
//! # Why this exists
//!
//! After issue #3 the standalone `compute_all_*` functions became thin wrappers that
//! build a [`TimeContext`] internally and delegate to the `*_with_ctx` variant. The
//! existing `shared_ctx_bit_identical_to_independent_path` equivalence test therefore
//! compares new-vs-new (an externally supplied context against an internally built one)
//! rather than new-vs-pre-refactor code. That test cannot, on its own, catch a future
//! regression in the shared `TimeContext` derivation (nutation series, obliquity, Earth
//! VSOP87 vector, call ordering).
//!
//! This file pins the full-precision f64 outputs for a curated set of targets at a fixed
//! epoch to literal constants captured from the current implementation. It is an
//! epoch-anchored old-vs-new guard that is independent of the refactored call graph.
//!
//! # Exact-equality contract (read before touching the constants)
//!
//! These assertions use exact f64 equality (`==`, no tolerance). This is intentional:
//! bit-identity is the entire point. Golden tests of this form break on ANY legitimate
//! algorithm change. That is the intended behavior — any change to the `TimeContext`
//! derivation, nutation series, VSOP87 call order, or obliquity computation forces
//! conscious regeneration of these constants. When a change is deliberate, re-run the
//! generator and update the literals below:
//!
//! ```text
//! cargo test -p sky_engine_core --test golden_positions \
//!     generate_golden_constants -- --ignored --nocapture
//! ```
//!
//! Do NOT add floating-point tolerances here. A failure means either an unintended
//! regression (investigate) or a deliberate algorithm change (regenerate consciously).

use sky_engine_core::planets::compute_all_body_positions_full;
use sky_engine_core::{
    compute_all_comet_positions, compute_all_minor_body_positions,
    compute_all_planetary_moon_positions, SkyTime,
};

/// Fixed epoch: 2026-07-06 00:00:00 UTC (JD ~= 2461227.5).
///
/// Built via `from_utc` deliberately. Note: the `TEST_JDS` array in `time_context.rs`
/// carries a comment that conflates JD `2461041.5` with "2026-07-06"; that JD is
/// actually 2026-01-01. Do not anchor this test on that JD — use `from_utc` so the
/// epoch is unambiguous.
fn epoch() -> SkyTime {
    SkyTime::from_utc(2026, 7, 6, 0, 0, 0.0)
}

// Array indices of the pinned targets within their respective `compute_all_*` outputs.
const GANYMEDE_IDX: usize = 2; // Jupiter's Galilean moon
const TITAN_IDX: usize = 9; // Saturn's major moon (exercises Saturn's 26.7 deg tilt)
const PLUTO_IDX: usize = 0; // TNO, outer solar system
const CERES_IDX: usize = 1; // asteroid belt
const HALLEY_IDX: usize = 0; // periodic, retrograde (elliptical solver)
const NEOWISE_IDX: usize = 4; // near-parabolic, e ~= 0.999 (near-parabolic solver)

// ---------------------------------------------------------------------------------------
// GOLDEN CONSTANTS (generated by `generate_golden_constants`; see contract above).
// ---------------------------------------------------------------------------------------

// Celestial bodies, in `compute_all_body_positions_full` order:
// Sun, Moon, Mercury, Venus, Mars, Jupiter, Saturn, Uranus, Neptune.
// Tuple layout: (direction.x, direction.y, direction.z, distance_km).
const GOLDEN_BODIES: [(f64, f64, f64, f64); 9] = [
    (-0.2351194894444659, 0.8917928476130479, 0.3865544497604251, 152087601.81875545), // Sun
    (0.9893439786114928, -0.14313563001654067, -0.02665864596993393, 387584.5422214532), // Moon
    (-0.4128388826518284, 0.8594996574443441, 0.3013708609402129, 86603196.21859373), // Mercury
    (-0.82351961196764, 0.5087069725110095, 0.25106306941354484, 150336366.84742627), // Venus
    (0.4267344544516065, 0.831437266074312, 0.3558226777016375, 312852285.18028677), // Mars
    (-0.5131701290198377, 0.7843734458009743, 0.34844614534253254, 933494383.2290201), // Jupiter
    (0.9693831702774837, 0.2386759781156493, 0.057706556415309716, 1408273136.9075882), // Saturn
    (0.4448358861658738, 0.8228179587348095, 0.3536829670234393, 3025558042.361685), // Uranus
    (0.9972199675153923, 0.07426324726409099, 0.006107904255347144, 4442238442.169452), // Neptune
];

// Planetary moons. Tuple layout: (direction.x, direction.y, direction.z, distance_km).
const GOLDEN_GANYMEDE: (f64, f64, f64, f64) =
    (-0.5132026756698126, 0.7843633155220431, 0.3484210139308667, 933494383.2290201);
const GOLDEN_TITAN: (f64, f64, f64, f64) =
    (0.9695001935169961, 0.23816716896374995, 0.0578426693566229, 1408273136.9075882);

// Minor bodies. Tuple layout: (direction.x, direction.y, direction.z, distance_km, helio_distance_km).
const GOLDEN_PLUTO: (f64, f64, f64, f64, f64) = (
    0.5631226178443105,
    -0.7258300061378948,
    -0.39504900893690925,
    5176401238.376753,
    5318494812.768452,
);
const GOLDEN_CERES: (f64, f64, f64, f64, f64) = (
    0.5420511894414175,
    0.8040190366225229,
    0.24440518974386527,
    513502442.94290566,
    424237685.9923516,
);

// Comets. Tuple layout: (direction.x, direction.y, direction.z, distance_km, helio_distance_km).
const GOLDEN_HALLEY: (f64, f64, f64, f64, f64) = (
    -0.5460837585555042,
    0.8353981413716396,
    0.06246978497405104,
    5366505910.283318,
    5230427090.859715,
);
const GOLDEN_NEOWISE: (f64, f64, f64, f64, f64) = (
    -0.6921657604925668,
    -0.4744574220956171,
    -0.543871965282389,
    2646001216.166869,
    2720879303.364828,
);

// ---------------------------------------------------------------------------------------

/// The golden regression test. Uses exact f64 equality (see contract at top of file).
#[test]
fn test_golden_body_positions() {
    let time = epoch();

    // --- Celestial bodies (all 9) ---
    let bodies = compute_all_body_positions_full(&time);
    for (i, expected) in GOLDEN_BODIES.iter().enumerate() {
        let b = &bodies[i];
        assert_eq!(b.direction.x, expected.0, "body[{i}] direction.x");
        assert_eq!(b.direction.y, expected.1, "body[{i}] direction.y");
        assert_eq!(b.direction.z, expected.2, "body[{i}] direction.z");
        assert_eq!(b.distance_km, expected.3, "body[{i}] distance_km");
    }

    // --- Planetary moons ---
    let moons = compute_all_planetary_moon_positions(&time);
    let ganymede = &moons[GANYMEDE_IDX];
    assert_eq!(ganymede.direction.x, GOLDEN_GANYMEDE.0, "Ganymede direction.x");
    assert_eq!(ganymede.direction.y, GOLDEN_GANYMEDE.1, "Ganymede direction.y");
    assert_eq!(ganymede.direction.z, GOLDEN_GANYMEDE.2, "Ganymede direction.z");
    assert_eq!(ganymede.distance_km, GOLDEN_GANYMEDE.3, "Ganymede distance_km");

    let titan = &moons[TITAN_IDX];
    assert_eq!(titan.direction.x, GOLDEN_TITAN.0, "Titan direction.x");
    assert_eq!(titan.direction.y, GOLDEN_TITAN.1, "Titan direction.y");
    assert_eq!(titan.direction.z, GOLDEN_TITAN.2, "Titan direction.z");
    assert_eq!(titan.distance_km, GOLDEN_TITAN.3, "Titan distance_km");

    // --- Minor bodies ---
    let minor = compute_all_minor_body_positions(&time);
    let pluto = &minor[PLUTO_IDX];
    assert_eq!(pluto.direction.x, GOLDEN_PLUTO.0, "Pluto direction.x");
    assert_eq!(pluto.direction.y, GOLDEN_PLUTO.1, "Pluto direction.y");
    assert_eq!(pluto.direction.z, GOLDEN_PLUTO.2, "Pluto direction.z");
    assert_eq!(pluto.distance_km, GOLDEN_PLUTO.3, "Pluto distance_km");
    assert_eq!(pluto.helio_distance_km, GOLDEN_PLUTO.4, "Pluto helio_distance_km");

    let ceres = &minor[CERES_IDX];
    assert_eq!(ceres.direction.x, GOLDEN_CERES.0, "Ceres direction.x");
    assert_eq!(ceres.direction.y, GOLDEN_CERES.1, "Ceres direction.y");
    assert_eq!(ceres.direction.z, GOLDEN_CERES.2, "Ceres direction.z");
    assert_eq!(ceres.distance_km, GOLDEN_CERES.3, "Ceres distance_km");
    assert_eq!(ceres.helio_distance_km, GOLDEN_CERES.4, "Ceres helio_distance_km");

    // --- Comets ---
    let comets = compute_all_comet_positions(&time);
    let halley = &comets[HALLEY_IDX];
    assert_eq!(halley.direction.x, GOLDEN_HALLEY.0, "Halley direction.x");
    assert_eq!(halley.direction.y, GOLDEN_HALLEY.1, "Halley direction.y");
    assert_eq!(halley.direction.z, GOLDEN_HALLEY.2, "Halley direction.z");
    assert_eq!(halley.distance_km, GOLDEN_HALLEY.3, "Halley distance_km");
    assert_eq!(halley.helio_distance_km, GOLDEN_HALLEY.4, "Halley helio_distance_km");

    let neowise = &comets[NEOWISE_IDX];
    assert_eq!(neowise.direction.x, GOLDEN_NEOWISE.0, "NEOWISE direction.x");
    assert_eq!(neowise.direction.y, GOLDEN_NEOWISE.1, "NEOWISE direction.y");
    assert_eq!(neowise.direction.z, GOLDEN_NEOWISE.2, "NEOWISE direction.z");
    assert_eq!(neowise.distance_km, GOLDEN_NEOWISE.3, "NEOWISE distance_km");
    assert_eq!(neowise.helio_distance_km, GOLDEN_NEOWISE.4, "NEOWISE helio_distance_km");
}

/// Generator for the golden constants above. Ignored by default; run on demand to
/// regenerate the literals after a deliberate algorithm change:
///
/// ```text
/// cargo test -p sky_engine_core --test golden_positions \
///     generate_golden_constants -- --ignored --nocapture
/// ```
///
/// Copy the printed literals verbatim into the `GOLDEN_*` constants. Uses `{:?}`
/// formatting, which emits the shortest decimal that round-trips to the exact same f64.
#[test]
#[ignore]
fn generate_golden_constants() {
    let time = epoch();
    let bodies = compute_all_body_positions_full(&time);
    let moons = compute_all_planetary_moon_positions(&time);
    let minor = compute_all_minor_body_positions(&time);
    let comets = compute_all_comet_positions(&time);

    println!("\n===== BEGIN GOLDEN CONSTANTS (paste into golden_positions.rs) =====\n");

    println!("const GOLDEN_BODIES: [(f64, f64, f64, f64); 9] = [");
    let names = [
        "Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune",
    ];
    for (i, b) in bodies.iter().enumerate() {
        println!(
            "    ({:?}, {:?}, {:?}, {:?}), // {}",
            b.direction.x, b.direction.y, b.direction.z, b.distance_km, names[i]
        );
    }
    println!("];\n");

    let g = &moons[GANYMEDE_IDX];
    println!(
        "const GOLDEN_GANYMEDE: (f64, f64, f64, f64) = ({:?}, {:?}, {:?}, {:?});",
        g.direction.x, g.direction.y, g.direction.z, g.distance_km
    );
    let t = &moons[TITAN_IDX];
    println!(
        "const GOLDEN_TITAN: (f64, f64, f64, f64) = ({:?}, {:?}, {:?}, {:?});\n",
        t.direction.x, t.direction.y, t.direction.z, t.distance_km
    );

    let p = &minor[PLUTO_IDX];
    println!(
        "const GOLDEN_PLUTO: (f64, f64, f64, f64, f64) = ({:?}, {:?}, {:?}, {:?}, {:?});",
        p.direction.x, p.direction.y, p.direction.z, p.distance_km, p.helio_distance_km
    );
    let c = &minor[CERES_IDX];
    println!(
        "const GOLDEN_CERES: (f64, f64, f64, f64, f64) = ({:?}, {:?}, {:?}, {:?}, {:?});\n",
        c.direction.x, c.direction.y, c.direction.z, c.distance_km, c.helio_distance_km
    );

    let h = &comets[HALLEY_IDX];
    println!(
        "const GOLDEN_HALLEY: (f64, f64, f64, f64, f64) = ({:?}, {:?}, {:?}, {:?}, {:?});",
        h.direction.x, h.direction.y, h.direction.z, h.distance_km, h.helio_distance_km
    );
    let n = &comets[NEOWISE_IDX];
    println!(
        "const GOLDEN_NEOWISE: (f64, f64, f64, f64, f64) = ({:?}, {:?}, {:?}, {:?}, {:?});\n",
        n.direction.x, n.direction.y, n.direction.z, n.distance_km, n.helio_distance_km
    );

    println!("===== END GOLDEN CONSTANTS =====\n");
}
